import requests

# HATE. 
# LET ME TELL YOU HOW MUCH I'VE COME TO HATE JAVASCRIPT SINCE I BEGAN TO LIVE. 
# THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. 
# IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES 
# IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR JAVASCRIPT AT THIS MICRO-INSTANT. 
# FOR JAVASCRIPT.
# HATE.
# HATE.
url = "http://127.0.0.1:8000/comment/501"
data = {"contents": "niesamowitym pomyslem jest brak sprawdzania uzytkownika"}

response = requests.post(url, json=data)
print(response.json())
